FROM registry.suse.com/bci/python:3.10

RUN mkdir /pms
COPY requirements_test.txt requirements.txt /pms
WORKDIR /pms
RUN zypper -n in python310-devel gcc gcc-c++ && pip3.10 install -r requirements_test.txt && rm -rf /var/cache

ENTRYPOINT ["sh", "-c"]
